### ISSUE TITLE
flowdock:status doesn't seem to be picking up GitLab env variables

### ISSUE THREAD

**Issue by vvarp** [rande/gitlab-ci-helper#1]
I am running gitlab-ci-helper within the GitLab CI runner context, however every attempt ends up with:

    Unable to fetch the project: Error: Client.Do error: "Get ///api/v3/projects/64?private_token=: unsupported protocol scheme \"\""

It looks like GitLab env variables aren't being picked up properly. Testing on fresh build from master.

**Comment by vvarp** [comment]
Scratch that, haven't realized GITLAB_HOST and GITLAB_TOKEN needs to be passed down from GitLab

**Comment by rande** [comment]
Yep, I should try to generate a error for empty values
