### ISSUE TITLE
Generated binaries should include version

### ISSUE THREAD

**Issue by plouc** [rande/gitlab-ci-helper#26]
For now every release ships with the same binary name, like `alpine-amd64-gitlab-ci-helper`, we should include version:
- `alpine-amd64-gitlab-ci-helper-v1.0.0` for tag
- `alpine-amd64-gitlab-ci-helper-a0debe5` without tag

**Comment by rande** [comment]
Why this is important ? never saw this pattern before.

**Comment by plouc** [comment]
Might be useful to easily know which version we have, especially if we provide alternate ways to install the tool.

Several projects use it:
- https://github.com/curl/curl/releases
- https://github.com/mholt/caddy/releases
- https://alpinelinux.org/downloads/
- …

But might not be that important if it’s only available via GitHub as it’s already part of the path.
